# Generated by Django 5.2.4 on 2025-12-19 14:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True, verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('renouvellement_auto', models.BooleanField(default=False, verbose_name='Renouvellement automatique')),
                ('telechargements_utilises', models.IntegerField(default=0, verbose_name='Téléchargements utilisés ce mois')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='AchatUnitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_achat', models.CharField(choices=[('epreuve', 'Épreuve'), ('corrige', 'Corrigé'), ('pack', 'Pack (Épreuve + Corrigé)'), ('livre', 'Livre')], max_length=20, verbose_name="Type d'achat")),
                ('objet_id', models.IntegerField(help_text="ID de l'épreuve, corrigé ou livre", verbose_name="ID de l'objet acheté")),
                ('objet_nom', models.CharField(max_length=255, verbose_name="Nom de l'objet")),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix payé')),
                ('date_achat', models.DateTimeField(auto_now_add=True, verbose_name="Date d'achat")),
            ],
            options={
                'verbose_name': 'Achat unitaire',
                'verbose_name_plural': 'Achats unitaires',
                'ordering': ['-date_achat'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant')),
                ('methode', models.CharField(choices=[('fedapay', 'FedaPay'), ('kkiapay', 'KKiaPay'), ('moov_money', 'Moov Money'), ('mtn_mobile', 'MTN Mobile Money')], max_length=50, verbose_name='Méthode de paiement')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence de transaction')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID de transaction externe')),
                ('date_paiement', models.DateTimeField(auto_now_add=True, verbose_name='Date de paiement')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='PlanAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du plan')),
                ('type_plan', models.CharField(choices=[('gratuit', 'Gratuit'), ('mensuel', 'Mensuel'), ('annuel', 'Annuel')], max_length=20, unique=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix')),
                ('limite_telechargements', models.IntegerField(default=0, help_text='0 = illimité', verbose_name='Limite de téléchargements')),
                ('description', models.TextField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage")),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
                'ordering': ['ordre', 'prix'],
            },
        ),
        migrations.CreateModel(
            name='Telechargement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contenu', models.CharField(choices=[('epreuve', 'Épreuve'), ('corrige', 'Corrigé'), ('livre', 'Livre')], max_length=20, verbose_name='Type de contenu')),
                ('objet_id', models.IntegerField(verbose_name="ID de l'objet téléchargé")),
                ('objet_nom', models.CharField(max_length=255, verbose_name="Nom de l'objet")),
                ('date_telechargement', models.DateTimeField(auto_now_add=True, verbose_name='Date de téléchargement')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
            ],
            options={
                'verbose_name': 'Téléchargement',
                'verbose_name_plural': 'Téléchargements',
                'ordering': ['-date_telechargement'],
            },
        ),
    ]
