# Generated by Django 5.2.4 on 2025-12-19 14:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieEpreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('trimestre1', '1er Trimestre'), ('trimestre2', '2ème Trimestre'), ('trimestre3', '3ème Trimestre'), ('semestre1', '1er Semestre'), ('semestre2', '2ème Semestre'), ('examen_blanc', 'Examen Blanc'), ('revision', 'Fiche de Révision')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('6eme', '6ème'), ('5eme', '5ème'), ('4eme', '4ème'), ('3eme', '3ème (BEPC)'), ('2nde', 'Seconde'), ('1ere', 'Première'), ('terminale', 'Terminale (BAC)')], max_length=50, unique=True)),
                ('niveau_ordre', models.IntegerField(default=0)),
                ('cycle', models.CharField(choices=[('college', 'Collège'), ('lycee', 'Lycée')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(default='📚', max_length=10)),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['niveau_ordre'],
            },
        ),
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('annee_scolaire', models.CharField(help_text='Ex: 2024-2025', max_length=9)),
                ('fichier', models.FileField(upload_to='epreuves/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('duree', models.IntegerField(blank=True, help_text='Durée en minutes', null=True)),
                ('coefficient', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('nombre_pages', models.IntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=25, help_text="Prix de l'épreuve seule (par défaut 25 FCFA)", max_digits=10)),
                ('est_gratuit', models.BooleanField(default=False, help_text="Accessible sans payer ni s'abonner")),
                ('disponible_achat_unitaire', models.BooleanField(default=True, help_text="Peut être acheté à l'unité")),
                ('disponible_abonnement', models.BooleanField(default=True, help_text='Accessible via abonnement')),
                ('nombre_telechargements', models.IntegerField(default=0)),
                ('nombre_achats', models.IntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='epreuves.categorieepreuve')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='epreuves.classe')),
            ],
            options={
                'verbose_name': 'Épreuve',
                'verbose_name_plural': 'Épreuves',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Corrige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='corriges/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=25, help_text='Prix du corrigé seul (par défaut 25 FCFA)', max_digits=10)),
                ('type_corrige', models.CharField(choices=[('officiel', 'Corrigé Officiel'), ('detaille', 'Corrigé Détaillé'), ('bareme', 'Barème de Notation')], default='detaille', max_length=20)),
                ('auteur', models.CharField(blank=True, max_length=200)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('epreuve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corrige', to='epreuves.epreuve')),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icone', models.CharField(default='📖', max_length=10)),
                ('couleur', models.CharField(default='#4F46E5', max_length=7)),
                ('classes', models.ManyToManyField(related_name='matieres', to='epreuves.classe')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='epreuve',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='epreuves.matiere'),
        ),
    ]
