# Generated by Django 5.2.4 on 2025-12-19 14:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('epreuves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(default='📚', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('auteur', models.CharField(max_length=200)),
                ('editeur', models.CharField(blank=True, max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=13)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, help_text='Prix du livre (75 FCFA minimum ou plus selon le livre)', max_digits=10)),
                ('couverture', models.ImageField(blank=True, upload_to='livres/couvertures/')),
                ('fichier', models.FileField(upload_to='livres/fichiers/%Y/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('nombre_pages', models.IntegerField(default=0)),
                ('annee_publication', models.IntegerField(blank=True, null=True)),
                ('langue', models.CharField(default='Français', max_length=50)),
                ('nombre_ventes', models.IntegerField(default=0)),
                ('note_moyenne', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('est_disponible', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='livres.categorielivre')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='epreuves.classe')),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
    ]
